# Generated by Django 4.1.2 on 2024-06-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('usu_user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('usu_clave', models.CharField(max_length=12)),
            ],
        ),
    ]
